version: "3"

services:
  db:
    image: mysql:8.0
    volumes:
      - ./db/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: toor123
      MYSQL_DATABASE: laravel

  php:
    hostname: "php"
    build:
      args:
        user: sammy
        uid: 1000
      context: ./src
    env_file:
      - ./src/.env
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    volumes:
      - ./src:/var/www
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/logs/:/var/log/nginx/
    ports:
      - 8008:80
    depends_on:
      - php